direction: up

confederation: ICW\n\n(International\nConfederation\nof Wizards) {
  shape: hexagon
}

ministry: Ministry of Magic (UK) {
  shape: hexagon
}
congress: Congress of Wizards (US) {
  shape: hexagon
}
ministry -> confederation: {
  style: {
    animated: true
  }
}
congress -> confederation

hogwarts: Hogwarts {
  shape: hexagon
}
hogwarts -> ministry: {
  style: {
    animated: true
  }
}

beauxbatons: Beauxbatons {
  shape: hexagon
}
beauxbatons -> ministry

ilvermorny: Ilvermorny {
  shape: hexagon
}
ilvermorny -> congress
