direction: up

vars: {
  styles: {
    classroom: {
      border-radius: 999
      stroke-width: 3
      stroke: "#007500"
      fill: "#00D100"
      fill-pattern: dots
    }
    classroomLinkAnimated: {
      animated: true
      stroke: "#007500"
      stroke-width: 3
    }
    classroomLink: {
      stroke: "#007500"
      stroke-width: 1
    }
  }
  classroom: {
    borderRadius: 999
    strokeWidth: 3
    stroke: "#007500"
    fill: "#00D100"
    fillPattern: dots
  }
  primaryColors: {
    button: {
      active: "#4baae5"
      border: black
    }
  }
}

ministry: Ministry of Magic {
  shape: hexagon
}
hogwarts: Hogwarts {
  shape: hexagon
}
beauxbatons: Beauxbatons {
  shape: hexagon
}

hogwarts -> ministry
beauxbatons -> ministry

crouch: Barty Crouch {
  shape: person
}

weasley: Arthur Weasley {
  shape: person
}

crouch -> ministry: Admin
weasley -> ministry: Teacher

dumbledore: Albus Dumbledore {
  shape: person
}

snape: Severus Snape {
  shape: person
}

dumbledore -> hogwarts: Admin
snape -> hogwarts: Teacher

maxime: Olympe Maxime {
  shape: person
}

molina: Coye Molina {
  shape: person
}

maxime -> beauxbatons: Admin
molina -> beauxbatons: Teacher

################
## CLASSROOMS ##
################

astronomy: Astronomy {
  style: {
    border-radius: ${classroom.borderRadius}
    stroke-width: ${classroom.strokeWidth}
    stroke: ${classroom.stroke}
    fill: ${classroom.fill}
    fill-pattern: ${classroom.fillPattern}
  }
}
astronomy -> hogwarts: Classroom {
  style: ${styles.classroomLinkAnimated}
}

potions: Potions {
  style: ${styles.classroom}
}
potions -> beauxbatons: Classroom {
  style: ${styles.classroomLink}
}

charms: Charms {
  style: ${styles.classroom}
}
charms -> hogwarts {
  style: ${styles.classroomLink}
}

other: Other {
  style: {
      border-radius: 999
      stroke-width: 3
      stroke: "#007500"
      fill: "#00D100"
      fill-pattern: dots
      multiple: true
    }
}
other -> hogwarts {
  style: ${styles.classroomLink}
}
