direction: up

confederation: ICW\n\n(International\nConfederation\nof Wizards) {
  shape: hexagon
}

ministry: Ministry of Magic (UK)
congress: Congress of Wizards (US)
ministry -> confederation
congress -> confederation

hogwarts: Hogwarts\nSchool of Witchcraft and Wizardry
hogwarts -> ministry

beauxbatons: Beauxbatons
beauxbatons -> ministry

ilvermorny: Ilvermorny
ilvermorny -> congress
